Develop Library mock up
serokell/edna pull request #26
Opened 2021-03-19 13:01 UTC by pva701

## Description

Representations for all four entities were implemented.

## Related issue(s)

https://issues.serokell.io/issue/EDNA-31

## :white_check_mark: Checklist for your Pull Request

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [ ] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Commit-and-PR-policy-4cf98e1a910a415d86b5f2491d9af1af).
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).

2021-03-22 13:41 UTC, sashasashasasha151 requested changes, later dismissed

2021-03-22 13:41 UTC, sashasashasasha151 commented on frontend/src/pages/library/LibraryPage.tsx
> +      ))}
![image](https://user-images.githubusercontent.com/25207759/111998686-51f91680-8b2d-11eb-95f3-523098831a0e.png)

2021-03-23 11:28 UTC, pva701 commented on frontend/src/pages/library/LibraryPage.tsx
> +      ))}
huita

2021-03-24 09:35 UTC, gromakovsky approved these changes
Seems to work fine.

2021-03-24 10:00 UTC, merged